### ISSUE TITLE
Split search implementation out of admin daemon

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#94] opened 2019-10-31 16:26 UTC
The search implementation is under development and tends to crash; which means the daemon/admin/login parts also crash.

This can be solved by splitting search implementation at `/search?q=…` would be split out of the main admin/login daemon.

**Comment by alleonhardt** [comment] 2021-05-01 13:19
Duplicate of #284

**Closed as completed by alleonhardt** 2021-05-01 13:19 UTC
