### ISSUE TITLE
GetBooks: Scrolling horizontally, should scroll horizontally not vertically

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#116] opened 2019-11-06 03:28 UTC
Go to:

1. https://clas-digital.uni-frankfurt.de/GetBooks.html?query=jahrhunderts&scanId=HC8T3DTG&fuzzyness=1#page50
2. Drag slider on right-hand-side (OCR) downwards
3. Observe that the quick-links in the top-right scrolls horizontally, and that the scan + OCR text areas scroll off the left.

(Though at least it scrolls!)

**Comment by alleonhardt** [comment] 2019-11-06 07:32
I am not sure if I understand you right. When scrolling down the OCR the quick-links should scroll horzontally, at the moment this is intended behaviour. Are you saying we should change this or are you refering to Point 3.). I am not sure what you mean by the ocr and scan scroll of the left. Normally it should be like this:

1. Drag slider on right-hand-side (OCR) downwards
2. Observe that the quick-links in the top-right scrolls horizontally, and that the scan + OCR text areas scroll down.

**Comment by sladen** [comment] 2019-11-08 04:00
`<div>` dimensions on this browser:

1. 1301x671 `<div class="pageContainer"/>`: 
2. 0504x671 `<div …>`
3. 2026x097 `<div id="SearchOpts">`
4. 2013x112 `<div …>`
5. 1973x048 `<div id="searchboxstuff">`
6. 1927x024 `<input id="srchbox">`

Right, okay.  The error only shows when the box is *collapsed*.  When the box is *expanded*, it works and appears fine.

**Comment by alleonhardt** [comment] 2019-11-08 13:42
I put some thought into it, we maybe have to debug it when we meet up today. There could be several issues causing this problem best way is probably to edit the css until it works. I am forcing the links to stay on one line by adding `white-space: nowrap` and together with `overflow: auto` this should force the link list to stay on one line and be scrollable horizontally. The important class is: `.linkliststyler` in GetBooks at line 147. This link list is embedded in a grid the parent class is defined by inline style inside div at GetBooks line 866

**Comment by alleonhardt** [comment] 2019-11-18 20:11
Fixed by the new GetBooks version on https://www.clas-digital.uni-frankfurt.de:9991/GetBooks.html?query=fuchs&scanId=NAI269W8&fuzzyness=0#page7

**Closed as completed by alleonhardt** 2019-11-18 20:11 UTC
