### ISSUE TITLE
Book Uploader not working

### ISSUE THREAD

**Issue by ekoehring** [ShadowItaly/clas-digital#222] opened 2020-05-06 15:04 UTC
https://www.clas-digital.uni-frankfurt.de/ private/write/UploadBook.html
tested with book W3424MEI

Finally tried it, no succes: Even after 10 minutes, all files show 0% progress.
![image](https://user-images.githubusercontent.com/40890481/81193270-769edb00-8fbb-11ea-835c-3e0177900285.png)
Will keep the tab open for another 30 minutes or so, but I think it is not working at all.

Quick feedback about when this will be fixed would be appreciated, as I have the meeting with PaulM tomorrow 11am, thanks!

**Comment by ekoehring** [comment] 2020-05-06 15:06
Oh, now the first file ahs been eaten, but it says "Server returned error: Error while creating readerInfo.json: [json.exception.type_error.302] type must be number, but is null"

Based on Pauls recommendation, I reloaded the page, which stopped the process.

**Comment by ekoehring** [comment] 2020-05-06 15:18
To reproduce, the book was downloaded from BSB and can be downloaded for the next week or so using this link: https://dafo.digitale-sammlungen.de/dafomain.php?zc=812583b5769268c909c0801c6fc40165 (165MB)

**Comment by alleonhardt** [comment] 2020-05-06 17:42
OK thanks for the feedback we are on it.

**Comment by alleonhardt** [comment] 2020-05-07 06:14
Should be fixed by  066e67d4d605cd05e5e00c9822e81dfb2eeec3cd and 27d4df6d3d3464f1414d66fe5d7ce20d249ee4f3 and 0c97a26fda036f7f36759b2ed92ae98443b08dc7. We will try to cherry pick the commits into the stable version, after testing on the development server.

**Comment by georgbuechner** [comment] 2020-05-07 07:37
Alex what exactly is the new regular expression, checking the correct input for pages and ocr, so I can change this in the help document?

**Comment by alleonhardt** [comment] 2020-05-07 07:43
The regular expression is: _0*([1-9][0-9]*)
Which means _ followed by any number of zeros, followed by digit unequal to 0 folllowed by any number of digits. 
Valid for example:
_0001.jpg   => Page 1
page_0003.jpg => Page 3
bsb1030412_0010.jpg => Page 10
_0005.png => Page 5
...

**Comment by ekoehring** [comment] 2020-05-07 10:44
Still didnt work. New error message (after clicking "speichern"):
"Server returned error: missing_access_rights"

**Comment by alleonhardt** [comment] 2020-05-07 11:40
Could you try again after logging out and logging in again once, manually. This is a known bug, that the user gets logged out by the server but is not notified about it. If the problem persists I will investigate it again.

**Comment by ekoehring** [comment] 2020-05-07 11:48
I think it worked. I first got "There are already files on the server, you must choose..." but could not scroll down. But then it changed to "Uploaded all files successfully! In order to find results in the new book you have to restart the server! (The Server automatically restarts over night)"

If you want to doublecheck, W3424MEI is the key.

**Comment by ekoehring** [comment] 2020-05-07 13:42
Nachtrag:

This is confusing:
![image](https://user-images.githubusercontent.com/40890481/81301401-4cabee00-9079-11ea-8a17-231802979a4d.png)
Should the fields "Ist alles korrekt?" change? When? They did not.

**Comment by georgbuechner** [comment] 2020-05-09 11:48
Can this issue be closed? The last comment should be moved to issue #162

**Comment by ekoehring** [comment] 2020-05-09 12:22
There is still the bug that every uploaded file results in the error message for duplicate files. But that is also mentioned in the other report, so yes, this one can be closed. Thank you!

**Comment by PaulMueller9x** [comment] 2020-05-13 15:24
![error](https://user-images.githubusercontent.com/65245329/81832162-79ab4580-953e-11ea-9fa5-7b2b5b9a5303.png)

Just received this error message, when I clicked to upload something.

**Comment by alleonhardt** [comment] 2020-05-14 06:24
The problem is, that the pages are not named correctly. Meaning page0001.jpg should be page_0001.jpg. The name page0001.jpg is in the old format.

I will improve the uploader to accept the old format as well again.

**Comment by georgbuechner** [comment] 2020-05-14 08:31
Just leave out the "_" maybe?

And sorry for not updating the help document.

**Comment by ekoehring** [comment] 2020-05-14 08:45
Paul, can you give us the link to the dowload page of the book you tried to upload, or, if you dont have it anymore, upload a few pages here?
It seems BSB is using several systems of naming their files, and they should all be recognised correctly and automatically (with you and me not having to worry about them), as BSB is our main source.

**Comment by alleonhardt** [comment] 2020-05-14 09:10
That would be great if we could have a list of all possible formats from the BSB so we can improve the uploader.

**Comment by ekoehring** [comment] 2020-05-14 09:56
Ok, so I start:
everything I downloaded in the past week from BSB had the following format:
bsb10050971.txt
bsb10050971_00001.jpg
with 10050971 being the BSB order ID and 00001 being the page number

**Comment by ekoehring** [comment] 2020-05-14 10:06
And the books I would like to add from biodiversity heritage library seem to have the following format (example: https://www.biodiversitylibrary.org/item/48692)
48692.txt
archivfrnaturg01berl_0000.jp2

(These would need to be tested, though, especially eg the structure of the .txt and whether we can work with .jp2)

**Comment by georgbuechner** [comment] 2020-05-14 10:13
do you have an ocr you could show us? I'm curious about the page numbers inside.

**Comment by ekoehring** [comment] 2020-05-14 10:28
From the biodoversity Library? Just click on the example link above (https://www.biodiversitylibrary.org/item/48692), and then "Dowload Content", "Download book". Other than with BSB, no need to order, they are directly available

**Comment by georgbuechner** [comment] 2020-05-14 10:36
It seems like they are doing good work. It is however a new format of ocrs, with however, really good quality, as far as I've seen so far. Once you decide to upload books from there, please tell us in advance, so we can work on reading the ocrs, with this new format

**Comment by PaulMueller9x** [comment] 2020-05-14 12:59
All books that I have downloaded also have this format. For example "bsb10044058_00001".
Here is the download link: https://dafo.digitale-sammlungen.de/dafomain.php?zc=0cae5a272376dca666dfcf3167627542&sprache=0

**Comment by georgbuechner** [comment] 2020-05-20 16:45
Are there any more issues concerning book upload, apart from #230? 
If no, we can close this issue, if any new issues occur, then those can be placed in a new issue?

**Comment by ekoehring** [comment] 2020-05-20 16:49
Yes, can be closed, but the format-collection should be available somewhere, thank you!

**Comment by georgbuechner** [comment] 2020-05-20 17:57
Sorry, what do you mean by the "format-collection"

**Comment by ekoehring** [comment] 2020-05-20 18:05
We were asked to document different formats of books we encounter.
##
BSB:
bsb10050971.txt
bsb10050971_00001.jpg
with 10050971 being the BSB order ID and 00001 being the page number

BDHL:
48692.txt for https://www.biodiversitylibrary.org/item/48692
pages not including this item number, eg. archivfrnaturg01berl_0000.jp2
##

**Closed as completed** 2020-05-24 16:47 UTC
Labels: bug, high priority
